<div class="d-flex justify-content-between align-items-center mb-3"><div><h1><?=$id?'View / Edit Planting':'Add Planting'?></h1><p class="text-muted">This planting remains separate from the master seed research record.</p></div><a class="btn btn-outline-secondary" href="<?=e(url('garden'))?>">Back to My Garden</a></div>
<form method="post" class="card card-body"><?=csrf_field()?><div class="row g-3">
<div class="col-md-6"><label class="form-label" for="garden-seed">Seed Library seed</label><select id="garden-seed" class="form-select" name="seed_id" required><option value="">Choose a seed</option><?php foreach($seeds as $seed):?><option value="<?=e($seed['id'])?>" <?=(int)($planting['seed_id']??0)===(int)$seed['id']?'selected':''?>><?=e($seed['seed_number'].' · '.$seed['name'].(($seed['variety']??'')!==''?' — '.$seed['variety']:''))?></option><?php endforeach?></select></div>
<div class="col-md-3"><label class="form-label" for="garden-date">Planted date</label><input id="garden-date" class="form-control" type="date" name="planted_date" value="<?=e($planting['planted_date']??'')?>" required></div>
<div class="col-md-3"><label class="form-label" for="garden-method">Planting method</label><select id="garden-method" class="form-select" name="planting_method" required><?php foreach(garden_methods() as $choice):?><option <?=($planting['planting_method']??'')===$choice?'selected':''?>><?=e($choice)?></option><?php endforeach?></select></div>
<div class="col-md-2"><label class="form-label" for="garden-quantity">Quantity</label><input id="garden-quantity" class="form-control" type="number" min="1" max="65535" name="quantity" value="<?=e($planting['quantity']??1)?>" required></div>
<div class="col-md-5"><label class="form-label" for="garden-location">Location / container / bed</label><input id="garden-location" class="form-control" maxlength="190" name="location" value="<?=e($planting['location']??'')?>" required></div>
<div class="col-md-5"><label class="form-label" for="garden-status">Status</label><select id="garden-status" class="form-select" name="status" required><?php foreach(garden_statuses() as $choice):?><option <?=($planting['status']??'')===$choice?'selected':''?>><?=e($choice)?></option><?php endforeach?></select></div>
<div class="col-md-6"><label class="form-label" for="garden-transplant">Actual transplant date</label><input id="garden-transplant" class="form-control" type="date" name="actual_transplant_date" value="<?=e($planting['actual_transplant_date']??'')?>"><div class="form-text">Authoritative; suppresses the expected transplant date.</div></div>
<div class="col-md-6"><label class="form-label" for="garden-harvest">Actual harvest date</label><input id="garden-harvest" class="form-control" type="date" name="actual_harvest_date" value="<?=e($planting['actual_harvest_date']??'')?>"><div class="form-text">Authoritative; suppresses the expected harvest date.</div></div>
<div class="col-12"><label class="form-label" for="garden-notes">Notes</label><textarea id="garden-notes" class="form-control" rows="5" maxlength="10000" name="notes"><?=e($planting['notes']??'')?></textarea></div><div class="col-12"><button class="btn btn-success">Save Planting</button></div></div></form>
