<?php
$show=fn(mixed $value): string => ($value===null || $value==='') ? 'Not recorded' : e($value);
$yesNo=fn(mixed $value): string => $value ? 'Yes' : 'No';
$range=function(string $prefix) use($seed): ?string {
    $start=date_label($seed[$prefix.'_start_month']??null,$seed[$prefix.'_start_day']??null);
    $end=date_label($seed[$prefix.'_end_month']??null,$seed[$prefix.'_end_day']??null);
    return (!$start && !$end) ? null : trim($start.($start&&$end?' – ':'').$end);
};
$row=function(string $label,mixed $value) use($show): void { ?><dt class="col-sm-5"><?=e($label)?></dt><dd class="col-sm-7"><?=$show($value)?></dd><?php };
$historyLabels=['category_id'=>'Category','plant_family_id'=>'Plant Family','status_id'=>'Seed Status','seed_number'=>'Seed Number','name'=>'Seed Name','variety'=>'Variety','packet_year'=>'Packet Year','days_to_maturity_min'=>'Maturity Minimum','days_to_maturity_max'=>'Maturity Maximum','maturity_qualifier'=>'Maturity Qualifier','indoor_start_status'=>'Indoor Start Status','direct_sow_status'=>'Direct Sow Status','transplant_status'=>'Transplant Status','plantable_months'=>'Plantable Months','perennial_status'=>'Perennial/Biennial Status','storage_box'=>'Storage Box','container'=>'Container','envelope'=>'Envelope','row_label'=>'Row','slot'=>'Slot','uses'=>'Garden Uses','companions'=>'Companion Planting','container_friendly'=>'Container Friendly','pollinator_friendly'=>'Pollinator Friendly','medicinal'=>'Medicinal','perennial'=>'Perennial','frost_tolerant'=>'Frost Tolerant','heat_tolerant'=>'Heat Tolerant','drought_tolerant'=>'Drought Tolerant','trellis_needed'=>'Trellis/Support Needed'];
$historyDisplay=function(string $key,mixed $value): mixed {
    if ($value===null || $value==='') return $value;
    if (in_array($key,['category_id','plant_family_id','status_id'],true) && ctype_digit((string)$value)) {
        $table=['category_id'=>'categories','plant_family_id'=>'plant_families','status_id'=>'statuses'][$key];
        $stmt=db()->prepare("SELECT name FROM $table WHERE id=?"); $stmt->execute([(int)$value]); return $stmt->fetchColumn() ?: 'Unknown';
    }
    if (in_array($key,seed_boolean_columns(),true) && in_array((string)$value,['0','1'],true)) return (int)$value===1?'Yes':'No';
    if ($key==='plantable_months' && preg_match('/^\d+(,\d+)*$/',(string)$value)) return implode(', ',array_map(fn($m)=>month_name((int)$m),explode(',',(string)$value)));
    return $value;
};
?>
<div class="d-flex flex-wrap justify-content-between gap-2 mb-3"><div><h1><?=e($seed['name'])?></h1><p class="lead">Seed # <?=e($seed['seed_number'])?></p></div><div class="d-flex flex-wrap gap-2"><a class="btn btn-success" href="<?=e(url('seeds/'.$seed['id'].'/edit'))?>">Edit</a><form method="post" action="<?=e(url('seeds/'.$seed['id'].'/duplicate'))?>"><?=csrf_field()?><button class="btn btn-outline-secondary">Duplicate</button></form><form method="post" action="<?=e(url('seeds/'.$seed['id'].'/delete'))?>" data-confirm="Delete this seed? Seed numbers are never auto-renumbered."><?=csrf_field()?><button class="btn btn-outline-danger">Delete</button></form></div></div>
<div class="row g-3">
<div class="col-12"><section class="card"><div class="card-body"><h2 class="h5">Basic Information</h2><dl class="row"><?php $row('Seed Number',$seed['seed_number']);$row('Seed Name',$seed['name']);$row('Variety',$seed['variety']);$row('Category',$seed['category_name']);$row('Plant Family',$seed['family_name']);$row('Plant Type',$seed['plant_type']);$row('Planting Method',$seed['planting_method']);$row('Seed Status',$seed['status_name']);$row('Created',$seed['created_at']);$row('Updated',$seed['updated_at']);?></dl></div></section></div>
<div class="col-12"><section class="card"><div class="card-body"><h2 class="h5">Planting Information</h2><dl class="row"><?php $row('Start Planting Date',date_label($seed['planting_start_month'],$seed['planting_start_day']));$row('Last Recommended Planting Date',date_label($seed['planting_end_month'],$seed['planting_end_day']));if(display_plantable_months())$row('Plantable Months',plantable_months_label($seed['plantable_months']));$row('Indoor Start',planting_availability_display($seed,'indoor'));$row('Direct Sow',planting_availability_display($seed,'direct_sow'));$row('Transplant',planting_availability_display($seed,'transplant'));$row('Indoor Start Weeks Before Frost',$seed['indoor_start_weeks_before_frost']!==null?$seed['indoor_start_weeks_before_frost'].' weeks':($seed['indoor_start_status']??null));$row('Transplant Weeks After Frost',$seed['transplant_weeks_after_frost']!==null?$seed['transplant_weeks_after_frost'].' weeks':($seed['transplant_status']??null));$row('Germination Days',($seed['days_to_germination_min']!==null||$seed['days_to_germination_max']!==null)?trim(($seed['days_to_germination_min']??'').'–'.($seed['days_to_germination_max']??''),'–').' days':null);$row('Harvest/Maturity',maturity_display($seed));$row('Succession Planting',$seed['succession_days']!==null?((int)$seed['succession_days']===0?'Not typically succession planted':$seed['succession_days'].' days'):null);?></dl></div></section></div>
<div class="col-12"><section class="card"><div class="card-body"><h2 class="h5">Growing Conditions</h2><dl class="row"><?php foreach(['ideal_soil_temperature'=>'Ideal Soil Temperature','sowing_depth'=>'Planting Depth','spacing'=>'Plant Spacing','row_spacing'=>'Row Spacing','thin_to_spacing'=>'Thin-To Spacing','sun_requirements'=>'Sun Requirements','water_requirements'=>'Water Needs','soil_requirements'=>'Soil Preference','minimum_container_size'=>'Minimum Container Size','plant_height'=>'Plant Height','perennial_status'=>'Perennial/Biennial Status'] as $key=>$label)$row($label,$seed[$key]); foreach(['container_friendly'=>'Container Friendly','trellis_needed'=>'Trellis/Support Needed','frost_tolerant'=>'Frost Tolerant','heat_tolerant'=>'Heat Tolerant','drought_tolerant'=>'Drought Tolerant','pollinator_friendly'=>'Pollinator Friendly','medicinal'=>'Medicinal'] as $key=>$label)$row($label,$yesNo($seed[$key]));?></dl></div></section></div>
<div class="col-12"><section class="card"><div class="card-body"><h2 class="h5">Garden Uses</h2><?= $uses?implode(' ',array_map(fn($use)=>'<span class="badge bg-secondary">'.e($use['name']).'</span>',$uses)):'<p class="text-muted">No garden uses recorded.</p>'?></div></section></div>
<div class="col-12"><section class="card"><div class="card-body"><h2 class="h5">Companion Planting</h2><?php if(!$companions):?><p class="text-muted">No companion relationships recorded.</p><?php else:?><div class="table-responsive"><table class="table"><thead><tr><th>Plant</th><th>Relationship</th><th>Notes</th></tr></thead><tbody><?php foreach($companions as $companion):?><tr><td><?=e($companion['name'])?></td><td><?=e($companion['relationship_type'])?></td><td><?=$show($companion['notes'])?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></div></section></div>
<div class="col-12"><section class="card"><div class="card-body"><h2 class="h5">Storage</h2><dl class="row"><?php foreach(['seed_source'=>'Seed Source/Brand','packet_year'=>'Packet Year','quantity'=>'Quantity Notes','purchase_date'=>'Purchase Date','expiration_year'=>'Expiration Year','storage_box'=>'Storage Box','container'=>'Container','envelope'=>'Envelope','row_label'=>'Row','slot'=>'Slot','location_notes'=>'Storage Notes'] as $key=>$label)$row($label,$seed[$key]);?></dl></div></section></div>
<div class="col-12"><section class="card"><div class="card-body"><h2 class="h5">Notes</h2><p><?=($seed['notes']??'')!==''?nl2br(e($seed['notes'])):'<span class="text-muted">Not recorded</span>'?></p></div></section></div>
<div class="col-12"><section class="card"><div class="card-body"><h2 class="h5">History</h2><?php if(!$history):?><p class="text-muted">No history recorded.</p><?php else:foreach($history as $entry):$changes=json_decode((string)$entry['changes_json'],true)?:[];?><article class="border-bottom py-2"><strong><?=e(ucfirst($entry['action']))?></strong> <span class="text-muted"><?=e($entry['created_at'])?><?= $entry['user_name']?' by '.e($entry['user_name']):''?></span><?php if($changes):?><ul class="mb-0"><?php foreach($changes as $key=>$change):if(!is_array($change)||!array_key_exists('before',$change))continue;?><li><strong><?=e($historyLabels[$key]??ucwords(str_replace('_',' ',$key)))?>:</strong> <?=$show($historyDisplay($key,$change['before']))?> → <?=$show($historyDisplay($key,$change['after']))?></li><?php endforeach;?></ul><?php endif;?></article><?php endforeach;endif;?></div></section></div>
</div>
