<?php
$v=fn(string $key, mixed $default=''): string=>e($seed[$key]??$default);
$rawMonths=$seed['plantable_months']??[]; $selectedMonths=is_array($rawMonths)?array_map('strval',$rawMonths):array_filter(explode(',',(string)$rawMonths));
$relationshipTypes=['Good Companion','Avoid','Neutral','Pest Deterrent','Trap Crop','Support Plant','Pollinator Support'];
$companionIndexes=array_values(array_filter(array_keys($companions),fn($key)=>is_int($key)||(is_string($key)&&ctype_digit($key))));
$nextCompanionIndex=$companionIndexes ? max(array_map('intval',$companionIndexes))+1 : 0;
$field=function(string $key,string $label,string $type='text',bool $required=false) use($v): void { ?><div class="col-md-4"><label class="form-label" for="<?=e($key)?>"><?=e($label)?><?= $required?' *':'' ?></label><input id="<?=e($key)?>" class="form-control" type="<?=e($type)?>" name="<?=e($key)?>" value="<?=$v($key)?>" <?= $required?'required':'' ?> <?= $type==='number'?'min="0"':'' ?>></div><?php };
$statusSelect=function(string $key,string $label) use($v): void { ?><div class="col-md-4"><label class="form-label" for="<?=e($key)?>"><?=e($label)?></label><select class="form-select" id="<?=e($key)?>" name="<?=e($key)?>"><option value="">No special status</option><?php foreach(['Not Recommended','Not Applicable'] as $status):?><option <?=($v($key)===$status)?'selected':''?>><?=e($status)?></option><?php endforeach?></select></div><?php };
$datePair=function(string $prefix,string $label,bool $required=false) use($v): void { ?><fieldset class="col-md-6"><legend class="form-label"><?=e($label)?><?= $required?' *':'' ?></legend><div class="input-group"><select class="form-select" aria-label="<?=e($label)?> month" name="<?=e($prefix)?>_month" <?= $required?'required':'' ?>><option value="">Month</option><?php for($m=1;$m<=12;$m++): ?><option value="<?=$m?>" <?=($v($prefix.'_month')==(string)$m)?'selected':''?>><?=e(month_name($m))?></option><?php endfor;?></select><input class="form-control" aria-label="<?=e($label)?> day" type="number" min="1" max="31" name="<?=e($prefix)?>_day" value="<?=$v($prefix.'_day')?>" placeholder="Day" <?= $required?'required':'' ?>></div></fieldset><?php };
?>
<div class="d-flex justify-content-between align-items-center"><h1><?= $id?'Edit Seed':'Add Seed' ?></h1></div>
<form method="post"><?=csrf_field()?>
<div class="card mb-3"><div class="card-body"><h2 class="h5">Basic Information</h2><div class="row g-3">
<?php $field('seed_number','Seed Number','text',true); $field('name','Seed Name','text',true); $field('variety','Variety'); ?>
<div class="col-md-4"><label for="category_id" class="form-label">Category *</label><select id="category_id" class="form-select" name="category_id" required><option value="">Choose</option><?php foreach($ref['categories'] as $r):?><option value="<?=e($r['id'])?>" <?=($seed['category_id']??'')==$r['id']?'selected':''?>><?=e($r['name'])?></option><?php endforeach;?></select></div>
<div class="col-md-4"><label for="plant_family_id" class="form-label">Plant Family</label><select id="plant_family_id" class="form-select" name="plant_family_id"><option value="">Choose</option><?php foreach($ref['families'] as $r):?><option value="<?=e($r['id'])?>" <?=($seed['plant_family_id']??'')==$r['id']?'selected':''?>><?=e($r['name'])?></option><?php endforeach;?></select></div>
<div class="col-md-4"><label for="status_id" class="form-label">Seed Status</label><select id="status_id" class="form-select" name="status_id"><option value="">Choose</option><?php foreach($ref['statuses'] as $r):?><option value="<?=e($r['id'])?>" <?=($seed['status_id']??'')==$r['id']?'selected':''?>><?=e($r['name'])?></option><?php endforeach;?></select></div>
<?php $field('plant_type','Plant Type'); ?><div class="col-md-4"><label for="planting_method" class="form-label">Planting Method *</label><select id="planting_method" class="form-select" name="planting_method" required><option value="">Choose</option><?php foreach(['Direct Sow','Start Indoors','Transplant','Direct Sow or Transplant'] as $m):?><option <?=($seed['planting_method']??'')===$m?'selected':''?>><?=e($m)?></option><?php endforeach;?></select></div>
</div></div></div>
<div class="card mb-3"><div class="card-body"><h2 class="h5">Planting Information</h2><div class="row g-3"><?php $datePair('planting_start','Start Planting Date',true); $datePair('planting_end','Last Recommended Planting Date',true); $statusSelect('indoor_start_status','Indoor Start Status'); $datePair('indoor_start','Indoor Start Range — Start'); $datePair('indoor_end','Indoor Start Range — End'); $statusSelect('direct_sow_status','Direct Sow Status'); $datePair('direct_sow_start','Direct Sow Range — Start'); $datePair('direct_sow_end','Direct Sow Range — End'); $statusSelect('transplant_status','Transplant Status'); $datePair('transplant_start','Transplant Range — Start'); $datePair('transplant_end','Transplant Range — End'); $field('days_to_germination_min','Germination Days — Minimum','number'); $field('days_to_germination_max','Germination Days — Maximum','number'); $field('days_to_maturity_min','Maturity Days — Minimum','number'); $field('days_to_maturity_max','Maturity Days — Maximum','number'); $field('maturity_qualifier','Maturity Qualifier'); $field('indoor_start_weeks_before_frost','Indoor Start Weeks Before Frost','number'); $field('transplant_weeks_after_frost','Transplant Weeks After Frost','number'); $field('succession_days','Succession Planting Days','number'); ?></div><fieldset class="mt-3"><legend class="form-label">Plantable Months</legend><div class="month-grid"><?php for($m=1;$m<=12;$m++):?><div class="form-check"><input id="month_<?=$m?>" class="form-check-input" type="checkbox" name="plantable_months[]" value="<?=$m?>" <?=in_array((string)$m,$selectedMonths,true)?'checked':''?>><label class="form-check-label" for="month_<?=$m?>"><?=e(month_name($m))?></label></div><?php endfor;?></div></fieldset></div></div>
<div class="card mb-3"><div class="card-body"><h2 class="h5">Growing Conditions</h2><div class="row g-3"><?php foreach(['ideal_soil_temperature'=>'Ideal Soil Temperature','sowing_depth'=>'Planting Depth','spacing'=>'Plant Spacing','row_spacing'=>'Row Spacing','thin_to_spacing'=>'Thin-To Spacing','sun_requirements'=>'Sun Requirements','water_requirements'=>'Water Needs','soil_requirements'=>'Soil Preference','minimum_container_size'=>'Minimum Container Size','plant_height'=>'Plant Height'] as $k=>$l)$field($k,$l); ?></div><div class="flag-grid mt-3"><?php foreach(['container_friendly'=>'Container Friendly','trellis_needed'=>'Trellis/Support Needed','frost_tolerant'=>'Frost Tolerant','heat_tolerant'=>'Heat Tolerant','drought_tolerant'=>'Drought Tolerant','pollinator_friendly'=>'Pollinator Friendly','medicinal'=>'Medicinal'] as $k=>$l):?><div class="form-check"><input id="<?=e($k)?>" class="form-check-input" type="checkbox" name="<?=e($k)?>" <?=!empty($seed[$k])?'checked':''?>><label for="<?=e($k)?>" class="form-check-label"><?=e($l)?></label></div><?php endforeach;?></div><div class="col-md-4 mt-3"><label for="perennial_status" class="form-label">Perennial/Biennial Status</label><select id="perennial_status" class="form-select" name="perennial_status"><option value="">Not specified</option><?php foreach(['Annual','Biennial','Perennial'] as $x):?><option <?=($seed['perennial_status']??'')===$x?'selected':''?>><?=$x?></option><?php endforeach;?></select></div></div></div>
<div class="row g-3"><div class="col-lg-6"><div class="card h-100"><div class="card-body"><h2 class="h5">Inventory & Storage</h2><div class="row g-3"><?php $field('seed_source','Seed Source/Brand'); $field('packet_year','Packet Year','number'); $field('quantity','Quantity Notes'); $field('purchase_date','Purchase Date','date'); $field('expiration_year','Expiration Year','number'); foreach(['storage_box'=>'Storage Box','container'=>'Container','envelope'=>'Envelope','row_label'=>'Row','slot'=>'Slot'] as $k=>$l)$field($k,$l);?></div><label for="location_notes" class="form-label mt-3">Storage Notes</label><textarea id="location_notes" class="form-control" name="location_notes"><?=$v('location_notes')?></textarea></div></div></div>
<div class="col-lg-6"><div class="card mb-3"><div class="card-body"><h2 class="h5">Garden Uses</h2><div class="flag-grid"><?php foreach($ref['uses'] as $u):?><div class="form-check"><input id="use_<?=e($u['id'])?>" class="form-check-input" type="checkbox" name="uses[]" value="<?=e($u['id'])?>" <?=in_array($u['id'],$selectedUses)?'checked':''?>><label for="use_<?=e($u['id'])?>" class="form-check-label"><?=e($u['name'])?></label></div><?php endforeach;?></div></div></div><div class="card"><div class="card-body"><label for="notes" class="form-label h5">Notes</label><textarea id="notes" class="form-control" name="notes" rows="6"><?=$v('notes')?></textarea></div></div></div></div>
<div class="card my-3"><div class="card-body"><h2 class="h5">Companion Planting</h2><p class="text-muted">Add as many structured relationships as needed. A companion and relationship type pair must be unique.</p><div id="companion-rows" data-next-index="<?=$nextCompanionIndex?>"><?php foreach($companions as $i=>$row):?><fieldset class="companion-row row g-2 mb-3"><legend class="visually-hidden">Companion <?=($i+1)?></legend><div class="col-md-4"><label class="form-label" for="comp_<?=$i?>">Companion</label><select id="comp_<?=$i?>" class="form-select" name="companions[<?=$i?>][companion_seed_id]"><option value="">Choose</option><?php foreach($allSeeds as $s):if(($s['id']??0)===$id)continue;?><option value="<?=e($s['id'])?>" <?=($row['companion_seed_id']??'')==$s['id']?'selected':''?>><?=e($s['name'].' #'.$s['seed_number'])?></option><?php endforeach;?></select></div><div class="col-md-3"><label class="form-label" for="ctype_<?=$i?>">Relationship</label><select id="ctype_<?=$i?>" class="form-select" name="companions[<?=$i?>][relationship_type]"><option value="">Choose</option><?php foreach($relationshipTypes as $t):?><option <?=($row['relationship_type']??'')===$t?'selected':''?>><?=e($t)?></option><?php endforeach;?></select></div><div class="col-md-4"><label class="form-label" for="cnote_<?=$i?>">Notes</label><input id="cnote_<?=$i?>" class="form-control" name="companions[<?=$i?>][notes]" value="<?=e($row['notes']??'')?>"></div><div class="col-md-1 d-flex align-items-end"><button type="button" class="btn btn-outline-danger remove-companion" aria-label="Remove companion">Remove</button></div></fieldset><?php endforeach;?></div><button type="button" class="btn btn-outline-success" id="add-companion">Add Companion</button><template id="companion-template"><fieldset class="companion-row row g-2 mb-3"><legend class="visually-hidden">Companion</legend><div class="col-md-4"><label class="form-label">Companion</label><select class="form-select" data-name="companion_seed_id"><option value="">Choose</option><?php foreach($allSeeds as $s):if(($s['id']??0)===$id)continue;?><option value="<?=e($s['id'])?>"><?=e($s['name'].' #'.$s['seed_number'])?></option><?php endforeach;?></select></div><div class="col-md-3"><label class="form-label">Relationship</label><select class="form-select" data-name="relationship_type"><option value="">Choose</option><?php foreach($relationshipTypes as $t):?><option><?=e($t)?></option><?php endforeach;?></select></div><div class="col-md-4"><label class="form-label">Notes</label><input class="form-control" data-name="notes"></div><div class="col-md-1 d-flex align-items-end"><button type="button" class="btn btn-outline-danger remove-companion" aria-label="Remove companion">Remove</button></div></fieldset></template></div></div>
<div class="form-actions sticky-bottom bg-light border-top py-3 d-flex flex-wrap gap-2"><button class="btn btn-success" name="save_action" value="save">Save</button><button class="btn btn-outline-success" name="save_action" value="add_another">Save and Add Another</button><button class="btn btn-outline-secondary" name="save_action" value="duplicate">Save and Duplicate</button><a class="btn btn-outline-dark" href="<?=e($id?url('seeds/'.$id):url('seeds'))?>">Cancel</a><?php if($id):?><button class="btn btn-outline-danger ms-auto" type="submit" formaction="<?=e(url('seeds/'.$id.'/delete'))?>" data-confirm="Delete this seed?" formnovalidate>Delete</button><?php endif;?></div>
</form>
