<?php
$queryString = http_build_query(array_filter($filters, fn($value) => $value !== '' && $value !== null));
$exportUrl = url('export?download=1&report=filtered&format=csv' . ($queryString ? '&' . $queryString : ''));
$sortUrl = function (string $column) use ($filters): string {
    $next = $filters;
    $next['sort'] = $column;
    $next['direction'] = strtoupper((string)($filters['direction'] ?? 'ASC')) === 'ASC' ? 'DESC' : 'ASC';
    return url('seeds?' . http_build_query($next));
};
?>
<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3">
  <h1>Seed Inventory</h1>
  <div>
    <a class="btn btn-success" href="<?= e(url('seeds/create')) ?>">Add Seed</a>
    <a class="btn btn-outline-success" href="<?= e($exportUrl) ?>">Export Filtered CSV</a>
    <a class="btn btn-outline-secondary" href="<?= e(url('print?report=inventory')) ?>">Print</a>
  </div>
</div>
<div class="accordion mb-3" id="filters"><div class="accordion-item"><h2 class="accordion-header"><button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#filterBody">Filters</button></h2><div id="filterBody" class="accordion-collapse collapse show"><div class="accordion-body"><form class="row g-2"><div class="col-md-4"><label class="form-label">Search</label><input class="form-control" name="search" value="<?= e($filters['search'] ?? '') ?>"></div><div class="col-md-2"><label class="form-label">Category</label><select class="form-select" name="category_id"><option value="">All</option><?php foreach($ref['categories'] as $r): ?><option value="<?= e($r['id']) ?>" <?= ($filters['category_id']??'')==$r['id']?'selected':'' ?>><?= e($r['name']) ?></option><?php endforeach; ?></select></div><div class="col-md-2"><label class="form-label">Plant Family</label><select class="form-select" name="plant_family_id"><option value="">All</option><?php foreach($ref['families'] as $r): ?><option value="<?= e($r['id']) ?>" <?= ($filters['plant_family_id']??'')==$r['id']?'selected':'' ?>><?= e($r['name']) ?></option><?php endforeach; ?></select></div><div class="col-md-2"><label class="form-label">Status</label><select class="form-select" name="status_id"><option value="">All</option><?php foreach($ref['statuses'] as $r): ?><option value="<?= e($r['id']) ?>" <?= ($filters['status_id']??'')==$r['id']?'selected':'' ?>><?= e($r['name']) ?></option><?php endforeach; ?></select></div><div class="col-md-2"><label class="form-label">Plant Month</label><select class="form-select" name="plantable_month"><option value="">All</option><?php for($m=1;$m<=12;$m++): ?><option value="<?= $m ?>" <?= ($filters['plantable_month']??'')==$m?'selected':'' ?>><?= e(month_name($m)) ?></option><?php endfor; ?></select></div>
<?php $textFilters=['plant_type'=>'Plant Type','planting_method'=>'Planting Method','seed_source'=>'Seed Source','packet_year'=>'Packet Year','storage_box'=>'Seed Location']; foreach($textFilters as $k=>$label): ?><div class="col-md-2"><label class="form-label"><?= e($label) ?></label><input class="form-control" name="<?= e($k) ?>" value="<?= e($filters[$k] ?? '') ?>"></div><?php endforeach; ?>
<?php $flags=['container_friendly'=>'Container','pollinator_friendly'=>'Pollinator','medicinal'=>'Medicinal','perennial'=>'Perennial','frost_tolerant'=>'Frost Tolerant','heat_tolerant'=>'Heat Tolerant','trellis_needed'=>'Trellis']; foreach($flags as $k=>$label): ?><div class="col-md-2"><label class="form-label"><?= e($label) ?></label><select class="form-select" name="<?= e($k) ?>"><option value="">All</option><option value="1" <?= ($filters[$k]??'')==='1'?'selected':'' ?>>Yes</option><option value="0" <?= ($filters[$k]??'')==='0'?'selected':'' ?>>No</option></select></div><?php endforeach; ?>
<div class="col-md-2"><label class="form-label">Sort</label><select class="form-select" name="sort"><option value="seed_number">Seed #</option><?php foreach(['name'=>'Name','category_name'=>'Category','family_name'=>'Family','packet_year'=>'Packet Year','status_name'=>'Status','planting_start_month'=>'Planting Start','storage_box'=>'Location'] as $key=>$label): ?><option value="<?= e($key) ?>" <?= ($filters['sort']??'')===$key?'selected':'' ?>><?= e($label) ?></option><?php endforeach; ?></select></div><div class="col-md-2"><label class="form-label">Direction</label><select class="form-select" name="direction"><option value="ASC" <?= strtoupper($filters['direction']??'ASC')==='ASC'?'selected':'' ?>>Ascending</option><option value="DESC" <?= strtoupper($filters['direction']??'ASC')==='DESC'?'selected':'' ?>>Descending</option></select></div>
<div class="col-12"><button class="btn btn-success">Apply Filters</button> <a class="btn btn-outline-secondary" href="<?= e(url('seeds')) ?>">Reset</a></div></form></div></div></div></div>
<div class="card desktop-table"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th><a href="<?= e($sortUrl('seed_number')) ?>">Seed #</a></th><th><a href="<?= e($sortUrl('name')) ?>">Name</a></th><th><a href="<?= e($sortUrl('category_name')) ?>">Category</a></th><th><a href="<?= e($sortUrl('family_name')) ?>">Family</a></th><th><a href="<?= e($sortUrl('planting_start_month')) ?>">Window</a></th><th><a href="<?= e($sortUrl('storage_box')) ?>">Location</a></th><th><a href="<?= e($sortUrl('status_name')) ?>">Status</a></th><th></th></tr></thead><tbody><?php foreach($seeds as $s): ?><tr><td class="fw-bold"><?= e($s['seed_number']) ?></td><td><a href="<?= e(url('seeds/'.$s['id'])) ?>"><?= e($s['name']) ?></a><div class="text-muted small"><?= e($s['variety']) ?></div></td><td><?= e($s['category_name']) ?></td><td><?= e($s['family_name']) ?></td><td><?= e(date_label($s['planting_start_month'],$s['planting_start_day'])) ?> – <?= e(date_label($s['planting_end_month'],$s['planting_end_day'])) ?></td><td><?= e(trim(($s['storage_box']??'').' '.($s['container']??'').' '.($s['slot']??''))) ?></td><td><?= e($s['status_name']) ?></td><td><a class="btn btn-sm btn-outline-success" href="<?= e(url('seeds/'.$s['id'].'/edit')) ?>">Edit</a></td></tr><?php endforeach; ?></tbody></table></div></div>
<div class="mobile-card"><?php foreach($seeds as $s): ?><div class="card mb-2"><div class="card-body"><h2 class="h5"><a href="<?= e(url('seeds/'.$s['id'])) ?>"><?= e($s['name']) ?></a></h2><p class="mb-1"><strong>#</strong> <?= e($s['seed_number']) ?> · <?= e($s['category_name']) ?></p><p class="mb-2 text-muted"><?= e(date_label($s['planting_start_month'],$s['planting_start_day'])) ?> – <?= e(date_label($s['planting_end_month'],$s['planting_end_day'])) ?></p><a class="btn btn-outline-success w-100" href="<?= e(url('seeds/'.$s['id'].'/edit')) ?>">Edit</a></div></div><?php endforeach; ?></div>
<?php if(!$seeds): ?><div class="alert alert-info">No seeds match the current filters.</div><?php endif; ?>
